################################################################################
###                                                                          ###
###         Identify Fall 2015 to Spring 2016 Progressions for PARCC         ###
###                                                                          ###
################################################################################

library(SGP)
library(plyr)
library(RSQLite)
library(data.table)

parcc.db <- "./PARCC/Data/PARCC_Data_LONG.sqlite"
PARCC_Data_LONG <- rbindlist(list(
			dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select ID, YEAR, CONTENT_AREA, GRADE, VALID_CASE from PARCC_Data_LONG_2015_2"),
			dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select ID, YEAR, CONTENT_AREA, GRADE, VALID_CASE from PARCC_Data_LONG_2016_1"),
			dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select ID, YEAR, CONTENT_AREA, GRADE, VALID_CASE from PARCC_Data_LONG_2016_2")))

PARCC_Data_LONG <- PARCC_Data_LONG[grep("_SS", CONTENT_AREA, invert =TRUE),]

PARCC_MATH<- PARCC_Data_LONG[!CONTENT_AREA %in% "ELA"]

math.prog <- courseProgressionSGP(PARCC_MATH, lag.direction="BACKWARD", year='2015_2016_2')


### 
###         MATHEMATICS
###


##
##    Algebra I
##

###   Fall to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
	#  There are some, but none with enough to form a cohort
	#  Does, however, bring up the question of whether these kids should be excluded from analyses

###   Spring to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[COUNT>500] # Major progressions
table(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT$CONTENT_AREA_by_GRADE_PRIOR_YEAR.2)

	####  Tenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.06"]$COUNT) # 12879
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.07"]$COUNT) # 69301
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 172247
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="GEOMETRY.CT"]$COUNT) # 1193

	####  Untenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_II.CT"]$COUNT) # 202
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_1.CT"]$COUNT) # 121
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_2.CT"]$COUNT) # 20
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_3.CT"]$COUNT) # 2


##
##    Geometry
##

###   Fall to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT) # 1101
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT" & CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 425
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT) # 260


###   Spring to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[COUNT>500] # ALL sgp.content.areas=c('PRE_ALGEBRA', 'SEC_MATH_I', 'SEC_MATH_II'),

	####  Tenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.07"]$COUNT) # 1496
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 5955
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_I.CT"]$COUNT)   # 104365
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_II.CT"]$COUNT)  # 2980

	####  Untenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="GEOMETRY.CT"]$COUNT)    # 2323 (repeaters)
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.06"]$COUNT) # 24
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_1.CT"]$COUNT) # 78
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_2.CT"]$COUNT) # 19
sum(math.prog$BACKWARD[['2015_2016.2']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_3.CT"]$COUNT) # 1


##
##    Algebra II
##

###   Fall to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="GEOMETRY.CT"]$COUNT)   # 966 - Might get over the hump with final data
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)  # 235
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT) # 439 - no repeater analyses

###   Spring to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[COUNT>500] # Major progressions

	####  Tenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="GEOMETRY.CT"]$COUNT)    # 67951
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_I.CT"]$COUNT)   # 11705
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 2913

	####  Untenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_II.CT"]$COUNT)  # 4317 (repeaters)
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.07"]$COUNT) # 36
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_1.CT"]$COUNT) # 203
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_2.CT"]$COUNT) # 59
sum(math.prog$BACKWARD[['2015_2016.2']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_3.CT"]$COUNT) # 94


##
##    Integrated Math 1
##

####		HARDLY ANY INTEGRATED MATH IN PRELIM DATA  --  CHECK THOROUGHLY WITH FINAL DATA

###   Fall to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="GEOMETRY.CT"]$COUNT)   # 1
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)  # 1
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT) # 0

###   Spring to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[COUNT>500] # Major progressions

	####  Tenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.07"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 

	####  Untenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.06"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_I.CT"]$COUNT)   # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="GEOMETRY.CT"]$COUNT)    # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_II.CT"]$COUNT)  # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_1.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_2.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_3.CT"]$COUNT) # 2


##
##    Integrated Math 2
##

####		HARDLY ANY INTEGRATED MATH IN PRELIM DATA  --  CHECK THOROUGHLY WITH FINAL DATA

###   Fall to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="GEOMETRY.CT"]$COUNT)   # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)  # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT) # 

###   Spring to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[COUNT>500] # Major progressions

	####  Tenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_1.CT"]$COUNT) # 

	####  Untenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.06"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.07"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_I.CT"]$COUNT)   # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="GEOMETRY.CT"]$COUNT)    # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_II.CT"]$COUNT)  # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_2.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_3.CT"]$COUNT) # 3


##
##    Integrated Math 3
##

####		HARDLY ANY INTEGRATED MATH IN PRELIM DATA  --  CHECK THOROUGHLY WITH FINAL DATA

###   Fall to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="GEOMETRY.CT"]$COUNT)   # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)  # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="INTEGRATED_MATH_1.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="INTEGRATED_MATH_2.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="INTEGRATED_MATH_3.CT"]$COUNT) # 

###   Spring to Spring progressions
math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[COUNT>500] # Major progressions

	####  Tenable Progressions
	####  Untenable Progressions
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.06"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.07"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="MATHEMATICS.08"]$COUNT) # 

sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_I.CT"]$COUNT)   # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="GEOMETRY.CT"]$COUNT)    # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="ALGEBRA_II.CT"]$COUNT)  # 

sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_1.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_2.CT"]$COUNT) # 
sum(math.prog$BACKWARD[['2015_2016.2']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.2=="INTEGRATED_MATH_3.CT"]$COUNT) # 


### 
###         ELA
###

PARCC_ELA <- PARCC_Data_LONG[CONTENT_AREA %in% "ELA"]
ela.prog <- courseProgressionSGP(PARCC_ELA, lag.direction="BACKWARD", year='2015_2016_2')

ela.prog$BACKWARD[['2015_2016.2']]$ELA.11[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(ela.prog$BACKWARD[['2015_2016.2']]$ELA.11[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ELA.10"]$COUNT) # 404
ela.prog$BACKWARD[['2015_2016.2']]$ELA.10[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
sum(ela.prog$BACKWARD[['2015_2016.2']]$ELA.10[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ELA.09"]$COUNT) # 351
ela.prog$BACKWARD[['2015_2016.2']]$ELA.09[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]

ela.prog$BACKWARD[['2015_2016.2']]$ELA.08[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
ela.prog$BACKWARD[['2015_2016.2']]$ELA.07[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
ela.prog$BACKWARD[['2015_2016.2']]$ELA.06[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
ela.prog$BACKWARD[['2015_2016.2']]$ELA.05[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
ela.prog$BACKWARD[['2015_2016.2']]$ELA.04[!is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]
